version: '3.9'

services:
  app:
    image: ${IMAGE}
    container_name: sotopong
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    volumes:
      - sotopong-data:/app/sotopong.db
    restart: unless-stopped

volumes:
  sotopong-data:
